name: PyDoll Tests Suite

on: push
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
      - name: Run tests with coverage
        run: |
          poetry run pytest -s -x --cov=pydoll -vv --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: tests
          name: PyDoll Tests
          fail_ci_if_error: true